########################################################################################################################
#                                                  BUG REPORT TEMPLATE                                                 #
########################################################################################################################

# 1.  Meta data.
# 2.  Initialise form.
# 3.  Introduction text.
# 4.  Email input.
# 5.  OS selection.
# 6.  Browser selection.
# 7.  Bug type.
# 8.  Severity.
# 9.  Problem summary.
# 10. Expected behaviour.
# 11. Steps to reproduce.
# 12. Actual Behaviour.
# 13. Additional Information.
# 14. Agree to terms.

# Meta Data

name: 🐞 Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "new"]
projects: ["NinjaMonkeyGames/12"]

# Initialise Form

body:

# Introduction Text

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the form below to provide detailed information about the bug.

# Email Input

  - type: input
    id: contact-email
    attributes:
      label: Contact Email
      description: Please provide an email where we can reach you if more information is needed.
      placeholder: email@example.com
    validations:
      required: true

# OS Selection

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

# Browser Selection

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Opera
        - Other
    validations:
      required: true

# Bug Type

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: Select the type of issue you are reporting.
      options:
        - Application Bug
        - Documentation Problem
    validations:
      required: true 

# Severity

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How serious is the problem?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

# Problem Summary

  - type: textarea
    id: problem-summary
    attributes:
      label: Problem Summary
      description: Please describe the issue in a few sentences.
      placeholder: A brief summary of the issue.
    validations:
      required: true

# Expected Behaviour

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true

# Steps To Reproduce

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list the steps to reproduce the issue.
      placeholder: "1. \n2. \n3."
    validations:
      required: true

# Actual Behaviour

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: What actually happened? 
    validations:
      required: true

# Additional Information

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information or context that might help us resolve the issue.
      placeholder: Additional context, error messages, or anything else that may be helpful.
    validations:
      required: false

# Agree To Terms

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this bug report, you agree to follow our [Code of Conduct](./CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of conduct.
    validations:
      required: true
