########################################################################################################################
#                                                     BUMP VERSION                                                     #
########################################################################################################################

name: Bump Version

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version
        run: |
          echo "Bumping version in ${environment_name} environment"

        # Setup NodeJS

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

        # Install dependencies

      - name: Install dependencies
        run: npm ci

        # Run Semantic Release

      - name: Run Semantic Release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --extends ./.config/release.config.js

        # Get current package version

      - name: Get new version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Echo the updated version

      - name: Output the updated version
        run: |
          echo "Updated version: ${{ steps.get_version.outputs.version }}"

