########################################################################################################################
#                                                  PRODUCTION WORKFLOW                                                 #
########################################################################################################################

name: Production Workflow

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:

  call-bump-version:
    name: Bump Version
    uses: ./.github/workflows/bump-version.yml
    with:
      environment_name: ${{ inputs.environment_name }}

  call-build-docker:
    name: Build Docker Image
    needs: call-bump-version
    uses: ./.github/workflows/build-docker.yml
    with:
      environment_name: ${{ inputs.environment_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
