########################################################################################################################
#                                                BUILD & PUSH DOCKER IMAGE                                             #
########################################################################################################################

name: Build Docker

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
    outputs:
      version:
        description: "The new semantic version"
        value: ${{ jobs.build-push-docker-image.outputs.version }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Confirm DockerHub Connection
        run: |
          echo "Attempting to pull DockerHub hello-world image to confirm connection..."
          docker pull hello-world

      - name: Show Docker info
        run: docker info

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image  
        run: |
          echo "Building with version: ${{ steps.extract_version.outputs.version }}"
          docker buildx build \
            --sbom=true \
            --provenance=true \
            --tag monkeyknuckles/markdownlint-cli2:latest \
            --tag monkeyknuckles/markdownlint-cli2:${{ steps.extract_version.outputs.version }} \
            --push .

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: monkeyknuckles/markdownlint-cli2
          provider: dockerhub
          short_description: 'README'
          readme_file: 'README.md'
