name: Markdown Lint                                       # Define the name of the workflow

on: [push, pull_request]                                  # Trigger the workflow on push and pull request events

jobs:                                                     # Initialise job
  lint:                                                   # Define a job named 'lint'

    runs-on: ubuntu-latest                                # Specifies the type of VM to provision

    container:                                            # Set container image
      image: monkeyknuckles/markdownlint-cli2             # Points to Markdownlint container

    steps:                                                # List of steps to execute
      - name: Checkout code                               # Checkout code label text
        uses: actions/checkout@v3                         # Use the checkout action to clone the repository

      - name: Copy markdownlint config                    # Copy Markdownlint configuration file label text
        run: cp /app/.markdownlint.yaml $GITHUB_WORKSPACE # Include the Markdown configuration file in the docker build

      - name: Run markdownlint-cli2                       # Set lint Markdownlint label text
        run: markdownlint-cli2 '**/*.md'                  # Lint all Markdown files
