########################################################################################################################
#                                                  PRODUCTION WORKFLOW                                                 #
########################################################################################################################

name: Production Workflow

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  call-commitlint:
    name: commitlint
    uses: ./.github/workflows/commitlint.yml
    with:
      environment_name: ${{ inputs.environment_name }}

  call-markdownlint:
    name: markdownlint
    uses: ./.github/workflows/markdownlint.yml
    with:
      environment_name: ${{ inputs.environment_name }}

  #call-cspell:
  #  name: spellcheck
  #  uses: ./.github/workflows/spellcheck.yml
  #  with:
  #    environment_name: ${{ inputs.environment_name }}

  call-bump-version:
    name: Bump Version
    needs:
      - call-markdownlint
      - call-commitlint
      #- call-cspell
    uses: ./.github/workflows/bump-version.yml
    with:
      environment_name: ${{ inputs.environment_name }}

  call-build:
    name: Build Docker Image
    needs: call-bump-version
    uses: ./.github/workflows/build-docker.yml
    with:
      environment_name: ${{ inputs.environment_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}