########################################################################################################################
#                                                     LINT SPELLING                                                    #
########################################################################################################################

# Set workflow label

name: Lint Spelling

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      message:
        required: false
        type: string

permissions:
  contents: read  # Grants read access to repository contents

# Setup Spellchecking Job

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    
    container:
      image: monkeyknuckles/cspell
      options: --user root

    steps:
    
    # Checkout Code

      - name: Checkout Code
        uses: actions/checkout@v4

    # Run cspell to Check All Project Files

      - name: Run cspell
        run: cspell --color --gitignore --no-cache --config .config/cspell.json "**/*"

